### ISSUE TITLE
Device tree doesn't build PERIOD

### ISSUE THREAD

**Issue by ghost** [PizzaG/android_device_blu_B130DL#3]
![Screenshot from 2023-02-02 08-49-43](https://user-images.githubusercontent.com/120631808/216388860-dee3ae2a-05ba-4f3c-809c-fc2bc27263de.png)
Seen updates to the device tree and went and resetup TWRP 12.1 for building. Apparently, with my luck, still doesn't build. Got TWRP 12.1 and cloned the device tree as needed. Still broken!!!! This device tree is kind of a waste of time. I mean why even release it knowing the shit won't build? Fucking idiot

**Comment by Lg-PWNd** [comment]
> 

Why be a rude piece of shit?

Since you are so fucking good fix it dummy

**Comment by PizzaG** [comment]
> ![Screenshot from 2023-02-02 08-49-43](https://user-images.githubusercontent.com/120631808/216388860-dee3ae2a-05ba-4f3c-809c-fc2bc27263de.png) Seen updates to the device tree and went and resetup TWRP 12.1 for building. Apparently, with my luck, still doesn't build. Got TWRP 12.1 and cloned the device tree as needed. Still broken!!!! This device tree is kind of a waste of time. I mean why even release it knowing the shit won't build? Fucking idiot

Your Childish mouth and combative attitude is the reason you were banned from my Telegram Group as well as the reason you have been reported to Github.  So first I would like to say, learn some general manners and human decency.  You make it blatantly obvious you are either 12 years old or a 45 year old man living in his mothers basement and clearly off his meds!  Secondly, I don't see you dumping and building up device trees, I don't see you updating and adapting trees, I don't see you contributing much of anything useful in general.  I personally don't think Android and this type of hobby is for you.  Now on to the actual tree.  It was originally dumped and built up for a TWRP version that's not 12.1.  It was building and booting perfectly fine on that TWRP version.  With that being said, updating a device tree for a newer version can be and is trial and error, as is much of anything Android and life in general.  If this was not the case, you would never see an OEM putting out an update for their devices based off the same Android version.  What that tells me is that even the guys who get payed the big bucks and do this for a living make mistakes and need to go back and fix or update stuff.  Also keep in mind I don't have the device, and have never have had it.  I did the device tree to help out the community and give a base starting point for those interested to either give feedback or build upon it.  After actually building the updated tree locally, it took me all of 5 minutes to identify and fix the 3 issues preventing you from building.  So with all that being said, the tree is "fixed" and in a buildable state.  I encourage you strongly to not use it nor anything else of mine as at this point, you are just plain not welcome.  Rather than make it private and possibly hurt those people who do actually care and would like to contribute in some way, I'm not.  I bid you farewell and Happy Trolling!!!
